export default [
  {
    id: 12345,
    title: 'Crêpes raffinées',
    slug: 'crepes-raffinees',
    thumbnail: 'https://images.pexels.com/photos/53483/strawberries-crepe-dessert-sweet-53483.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    author: 'John Deuf',
    difficulty: 'Facile',
    description: 'Simples mais toujours délicieuses',
    ingredients: [
      {
        id: 1,
        quantity: 375,
        unit: 'g',
        name: 'de farine tamisée',
      },
      {
        id: 2,
        quantity: 3,
        unit: 'pincées',
        name: 'de sel',
      },
      {
        id: 15,
        quantity: 50,
        unit: 'g',
        name: 'de sucre en poudre',
      },
      {
        id: 28,
        quantity: 6,
        unit: '',
        name: 'oeufs entiers',
      },
      {
        id: 4,
        quantity: 80,
        unit: 'g',
        name: 'de beurre fondu',
      },
      {
        id: 3,
        quantity: 1,
        unit: 'L',
        name: 'de lait',
      },
      {
        id: 845,
        quantity: 3,
        unit: 'cuillerées à soupe',
        name: 'de rhum ambré ou vieux',
      },
    ],
    instructions: [
      'Tamiser farine',
      'Rajouter le sucre et le sel',
      'Rajouter les oeufs tout en mélangeant',
      'Rajouter le beurre fondu tout en mélangeant',
      'Rajouter le lait petit à petit tout en mélangeant',
      'Rajouter le rhum  tout en mélangeant. À ce stade si vous fatiguez, n\'hésitez pas à vous en servir un petit verre avant d\'attaquer la suite.',
      'Laisser reposer une heure',
      'Faire cuire à la poele ou à la machine à crêpes.',
      'Dégustez !',
    ],
  },
  {
    id: 8965,
    title: 'Pizza Margherita',
    slug: 'pizza-margherita',
    thumbnail: 'https://images.pexels.com/photos/263041/pexels-photo-263041.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    author: 'Silvia Dital',
    difficulty: 'Moyen',
    description: 'Dans la pure tradition italienne',
    ingredients: [
      {
        id: 1,
        quantity: 500,
        unit: 'g',
        name: 'de farine T45',
      },
      {
        id: 3,
        quantity: 250,
        unit: 'cl',
        name: 'd\'eau',
      },
      {
        id: 131,
        quantity: 11,
        unit: 'g',
        name: 'de levure sèche de boulanger',
      },
      {
        id: 12,
        quantity: 4,
        unit: 'c à s',
        name: 'd\'huile d\'olive vierge-extra',
      },
      {
        id: 143,
        quantity: '1/2',
        unit: 'c à c',
        name: 'de sucre',
      },
      {
        id: 4,
        quantity: '1/4',
        unit: 'c à c',
        name: 'de sel',
      },
      {
        id: 78,
        quantity: 800,
        unit: 'g',
        name: 'de pulpe de tomates',
      },
      {
        id: 97,
        quantity: 400,
        unit: 'g',
        name: 'de mozzarella',
      },
    ],
    instructions: [
      'La pâte :',
      'Verser la farine dans un saladier, ajouter le sel et mélanger',
      'Ajouter la levure sèche, le sucre, le sel et mélanger',
      'Creuser un puit au centre, y verser l’eau',
      'Petit à petit, à l’aide d’une fourchette, y incorporer la farine',
      'Pétrir ensuite à la main ou dans un robot-pétrisseur, ajouter l’huile puis continuer à pétrir jusqu’à obtenir une pâte lisse',
      'La façonner en boule, la mettre dans un grand saladier et couvrir avec un linge propre',
      'Laisser la pâte lever pendant 2 heures (Elle doit doubler de volume)',
      'Dégazer la pâte sur un plan de travail, la pétrir rapidement à nouveau, puis l’étaler dans un moule à pizza ou sur une plaque de cuisson',
      'Etaler la pâte plus ou moins fine, selon l’épaisseur que vous voulez donner à la pizza',
      'Etaler si possible à la main, la pâte reste plus aérienne',
      'Faire lever la pâte étalée dans le moule pendant encore 1 heure',
      'La garniture :',
      'Ajouter la sauce tomate en la répartissant avec une petite louche, en laissant 1,5 cm de bord libre tout autour de la pâte.',
      'Ajouter la mozzarella préalablement coupée en dés (ou en tranches) et dégorgée',
      'La cuisson :',
      'Faire cuire la pizza à 210°C pendant 10 à 15 minutes',
      'Dès la sortie du four y ajouter quelques feuille de basilic frais et servir',
      'Dégustez !',
    ],
  },
];
